[build]
  publish = "build"
  command = "chmod +x netlify-prebuild.sh && ./netlify-prebuild.sh && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  CI = "false"
  REACT_APP_API_URL = "https://innovaiteprojectsbackend.onrender.com/api"
