[build]
  command = "npm run build"
  publish = "build"
  # Adding environment variables to prevent lint errors from failing build
  [build.environment]
    CI = "false"

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200